//
//  RemoteCarouselRenderer.swift
//  Discbot
//
//  Self-contained WebGL carousel visualization for the remote web client.
//  It deliberately has no CDN or framework dependency so the controller UI
//  remains available on an isolated LAN.
//

import Foundation

enum RemoteCarouselRenderer {
    static let styles = #"""
.carousel-viewport{position:relative;margin-top:16px;padding:0;overflow:hidden;background:radial-gradient(circle at 48% 36%,#16283c 0,#0a111b 58%,#070b11 100%);border-color:#30445d;min-height:510px}.carousel-viewport:focus-within{border-color:#4f79a8}.carousel-scene-head{position:absolute;z-index:2;inset:16px 16px auto 16px;display:flex;align-items:flex-start;justify-content:space-between;gap:16px;pointer-events:none}.carousel-scene-head>*{pointer-events:auto}.carousel-scene-head h3{font-size:16px}.scene-kicker{display:flex;align-items:center;gap:8px;color:#b7c8dc;font-size:12px;font-weight:700}.scene-kicker:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 12px #51d393}.scene-actions{display:flex;gap:7px}.scene-actions button{padding:7px 10px;min-height:34px;background:#101a27cc;backdrop-filter:blur(10px);font-size:13px}.carousel-canvas{display:block;width:100%;height:510px;touch-action:none;cursor:grab;outline:none}.carousel-canvas.dragging{cursor:grabbing}.scene-help{position:absolute;z-index:2;left:16px;bottom:14px;padding:8px 11px;border:1px solid #2a3a4d;border-radius:9px;background:#08101acc;color:#a8b7c9;font-size:12px;pointer-events:none;backdrop-filter:blur(8px)}.scene-inspector{position:absolute;z-index:2;right:16px;bottom:14px;width:min(330px,calc(100% - 32px));padding:12px 14px;border:1px solid #35506e;border-radius:11px;background:#0c1622e8;box-shadow:0 12px 34px #0008;backdrop-filter:blur(12px)}.scene-inspector strong{display:block;font-size:17px}.scene-inspector p{margin:2px 0 0}.scene-slot-actions{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;margin-top:11px}.scene-slot-actions button{padding:7px 5px;min-height:34px;font-size:12px}.scene-legend{display:flex;gap:13px;align-items:center;flex-wrap:wrap;margin:11px 2px 0;color:var(--muted);font-size:12px}.legend-item{display:flex;align-items:center;gap:6px}.legend-swatch{width:9px;height:9px;border-radius:3px;background:#7d91aa}.legend-swatch.audio{background:#b68cff}.legend-swatch.dvd{background:#ffbd69}.legend-swatch.data{background:#69a9ff}.legend-swatch.ripped{background:#51d393}.legend-swatch.active{background:#e6f5ff;box-shadow:0 0 8px #69a9ff}.visualization-note{margin:8px 2px 0;font-size:12px}.webgl-fallback{position:absolute;inset:0;display:grid;place-items:center;padding:60px;text-align:center;color:var(--muted)}@media(max-width:760px){.carousel-viewport{min-height:430px}.carousel-canvas{height:430px}.carousel-scene-head{inset:12px 12px auto}.scene-help{display:none}.scene-inspector{right:12px;bottom:12px;left:12px;width:auto}.scene-actions button{padding:7px 9px}.scene-slot-actions{grid-template-columns:repeat(2,minmax(0,1fr))}.scene-legend{gap:9px}.carousel-scene-head .muted{display:none}}
"""#

    static let markup = #"""
<section class="panel carousel-viewport" aria-label="Live 3D carousel visualization">
  <div class="carousel-scene-head">
    <div><div class="scene-kicker">Live inventory</div><h3>200-slot changer cutaway</h3><span class="muted">Visualization only</span></div>
    <div class="scene-actions"><button id="carouselMotionButton" type="button" aria-pressed="true" onclick="toggleCarouselMotion()">Pause motion</button><button type="button" onclick="resetCarouselView()">Reset view</button></div>
  </div>
  <canvas id="carouselCanvas" class="carousel-canvas" tabindex="0" aria-label="Interactive three-dimensional view of the 200-slot disc carousel. Drag to orbit, scroll to zoom, and select a disc for details."></canvas>
  <div id="carouselWebGLFallback" class="webgl-fallback hidden">This browser could not start the 3D view. Inventory and carousel controls remain available below.</div>
  <div class="scene-help">Drag to orbit · Scroll to zoom · Select a disc</div>
  <div id="carouselInspector" class="scene-inspector"><span class="eyebrow">Carousel</span><strong id="carouselInspectorTitle">No slot selected</strong><p id="carouselInspectorDetail" class="muted">Select a disc to inspect its live state.</p><div class="scene-slot-actions" aria-label="Selected slot actions"><button id="slotLoadButton" type="button" disabled onclick="performSelectedSlotAction('load')">Load</button><button id="slotMountButton" type="button" disabled onclick="performSelectedSlotAction('mount')">Mount</button><button id="slotUnmountButton" type="button" disabled onclick="performSelectedSlotAction('unmount')">Unmount</button><button id="slotEjectButton" class="danger" type="button" disabled onclick="performSelectedSlotAction('eject')">Eject</button></div></div>
</section>
<div class="scene-legend" aria-label="Carousel color legend"><span class="legend-item"><i class="legend-swatch audio"></i>Audio</span><span class="legend-item"><i class="legend-swatch dvd"></i>DVD</span><span class="legend-item"><i class="legend-swatch data"></i>Data</span><span class="legend-item"><i class="legend-swatch ripped"></i>Ripped</span><span class="legend-item"><i class="legend-swatch active"></i>Active slot</span></div>
<p class="visualization-note muted">The model follows live inventory and hardware operations. Moving the view never sends a command to the changer.</p>
"""#

    static let script = #"""
class DiscbotCarousel3D {
  constructor(canvas,fallback){
    this.canvas=canvas;this.fallback=fallback;this.gl=canvas.getContext('webgl',{antialias:true,alpha:true,premultipliedAlpha:false})||canvas.getContext('experimental-webgl');
    this.slots=[];this.selected=0;this.active=0;this.carouselAngle=0;this.targetCarouselAngle=0;this.cameraYaw=-0.68;this.cameraPitch=0.48;this.distance=14.5;this.motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;this.dragging=false;this.dragDistance=0;this.lastTime=performance.now();this.transfer=null;this.hiddenSlot=0;this.pickPoints=[];
    if(!this.gl){fallback.classList.remove('hidden');return}
    try{this.setupGL();this.setupInput();this.resize();this.rebuild();requestAnimationFrame(t=>this.frame(t))}catch(e){console.error(e);fallback.classList.remove('hidden');this.gl=null}
  }
  setupGL(){
    const gl=this.gl,vs=`attribute vec3 aPosition;attribute vec3 aNormal;attribute vec4 aColor;uniform mat4 uViewProjection;uniform mat4 uModel;varying vec3 vNormal;varying vec4 vColor;varying float vDepth;void main(){vec4 world=uModel*vec4(aPosition,1.0);gl_Position=uViewProjection*world;vNormal=normalize(mat3(uModel)*aNormal);vColor=aColor;vDepth=gl_Position.z/gl_Position.w;}`,
      fs=`precision mediump float;varying vec3 vNormal;varying vec4 vColor;varying float vDepth;void main(){vec3 light=normalize(vec3(-0.35,0.82,0.46));float diffuse=max(dot(normalize(vNormal),light),0.0);float rim=pow(1.0-max(abs(vNormal.z),0.0),2.0)*0.18;float shade=0.38+diffuse*0.62+rim;vec3 color=vColor.rgb*shade;float fog=smoothstep(0.76,1.0,vDepth);gl_FragColor=vec4(mix(color,vec3(0.035,0.055,0.082),fog*.58),vColor.a);}`;
    const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};
    this.program=gl.createProgram();gl.attachShader(this.program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(this.program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));
    this.locations={position:gl.getAttribLocation(this.program,'aPosition'),normal:gl.getAttribLocation(this.program,'aNormal'),color:gl.getAttribLocation(this.program,'aColor'),vp:gl.getUniformLocation(this.program,'uViewProjection'),model:gl.getUniformLocation(this.program,'uModel')};
    this.carouselMesh=this.makeMesh();this.machineMesh=this.makeMesh();this.movingMesh=this.makeMesh();gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.clearColor(0,0,0,0);
  }
  makeMesh(){return{vertex: this.gl.createBuffer(),index:this.gl.createBuffer(),count:0}}
  upload(mesh,b){const gl=this.gl,data=new Float32Array(b.vertices),indices=new Uint16Array(b.indices);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.vertex);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,mesh.index);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,indices,gl.STATIC_DRAW);mesh.count=indices.length}
  builder(){const b={vertices:[],indices:[]};b.quad=(a,c,d,e,n,color)=>{const k=b.vertices.length/10;for(const p of[a,c,d,e])b.vertices.push(p[0],p[1],p[2],n[0],n[1],n[2],color[0],color[1],color[2],color[3]??1);b.indices.push(k,k+1,k+2,k,k+2,k+3)};b.box=(center,size,color,angle=0)=>{const[x,y,z]=center,[sx,sy,sz]=size,c=Math.cos(angle),s=Math.sin(angle),tr=p=>[x+p[0]*c-p[2]*s,y+p[1],z+p[0]*s+p[2]*c],ns=n=>[n[0]*c-n[2]*s,n[1],n[0]*s+n[2]*c],p=[[-sx/2,-sy/2,-sz/2],[sx/2,-sy/2,-sz/2],[sx/2,sy/2,-sz/2],[-sx/2,sy/2,-sz/2],[-sx/2,-sy/2,sz/2],[sx/2,-sy/2,sz/2],[sx/2,sy/2,sz/2],[-sx/2,sy/2,sz/2]];for(const f of[[0,3,2,1,[0,0,-1]],[4,5,6,7,[0,0,1]],[0,4,7,3,[-1,0,0]],[1,2,6,5,[1,0,0]],[3,7,6,2,[0,1,0]],[0,1,5,4,[0,-1,0]]])b.quad(tr(p[f[0]]),tr(p[f[1]]),tr(p[f[2]]),tr(p[f[3]]),ns(f[4]),color)};return b}
  rgba(hex,a=1){const v=parseInt(hex.slice(1),16);return[((v>>16)&255)/255,((v>>8)&255)/255,(v&255)/255,a]}
  addCylinder(b,r,y,height,color,segments=48){for(let i=0;i<segments;i++){const a=i*Math.PI*2/segments,n=(i+1)*Math.PI*2/segments,p=a=>[Math.cos(a)*r,y,Math.sin(a)*r],q=a=>[Math.cos(a)*r,y+height,Math.sin(a)*r],normal=[Math.cos((a+n)/2),0,Math.sin((a+n)/2)];b.quad(p(a),p(n),q(n),q(a),normal,color)}for(let i=0;i<segments;i++){const a=i*Math.PI*2/segments,n=(i+1)*Math.PI*2/segments;b.quad([0,y+height,0],[Math.cos(a)*r,y+height,Math.sin(a)*r],[Math.cos(n)*r,y+height,Math.sin(n)*r],[0,y+height,0],[0,1,0],color)}}
  addRing(b,inner,outer,y,color,segments=64){for(let i=0;i<segments;i++){const a=i*Math.PI*2/segments,n=(i+1)*Math.PI*2/segments,point=(r,t)=>[Math.cos(t)*r,y,Math.sin(t)*r];b.quad(point(inner,a),point(outer,a),point(outer,n),point(inner,n),[0,1,0],color)}}
  addDisc(b,angle,color,radius=1.12,centerRadius=3.72,centerY=1.3,thickness=.024){const radial=[Math.cos(angle),0,Math.sin(angle)],tangent=[-Math.sin(angle),0,Math.cos(angle)],segments=16,hole=.16;for(let i=0;i<segments;i++){const a=i*Math.PI*2/segments,n=(i+1)*Math.PI*2/segments;for(const side of[-1,1]){const point=(r,t)=>[radial[0]*(centerRadius+Math.cos(t)*r)+tangent[0]*thickness*side,centerY+Math.sin(t)*r,radial[2]*(centerRadius+Math.cos(t)*r)+tangent[2]*thickness*side],normal=[tangent[0]*side,0,tangent[2]*side];const p1=point(hole,a),p2=point(radius,a),p3=point(radius,n),p4=point(hole,n);side>0?b.quad(p1,p2,p3,p4,normal,color):b.quad(p4,p3,p2,p1,normal,color)}const outer=t=>[radial[0]*(centerRadius+Math.cos(t)*radius),centerY+Math.sin(t)*radius,radial[2]*(centerRadius+Math.cos(t)*radius)],o1=outer(a),o2=outer(n),normal=[radial[0]*Math.cos((a+n)/2),Math.sin((a+n)/2),radial[2]*Math.cos((a+n)/2)];b.quad([o1[0]+tangent[0]*thickness,o1[1],o1[2]+tangent[2]*thickness],[o1[0]-tangent[0]*thickness,o1[1],o1[2]-tangent[2]*thickness],[o2[0]-tangent[0]*thickness,o2[1],o2[2]-tangent[2]*thickness],[o2[0]+tangent[0]*thickness,o2[1],o2[2]+tangent[2]*thickness],normal,color)}}
  colorFor(slot){if(slot.exception)return this.rgba('#ff6875');if(slot.backupStatus==='ripped')return this.rgba('#51d393');const t=(slot.discType||'').toLowerCase();if(t.includes('audio'))return this.rgba('#b68cff');if(t.includes('dvd'))return this.rgba('#ffbd69');if(t.includes('data')||t.includes('mixed'))return this.rgba('#69a9ff');return this.rgba('#8294a9')}
  rebuild(){if(!this.gl)return;const b=this.builder(),dark=this.rgba('#26384c'),metal=this.rgba('#53677d'),rail=this.rgba('#34485e');this.addCylinder(b,5.05,-.28,.18,dark);this.addRing(b,1.18,4.98,-.08,this.rgba('#33485f'));this.addCylinder(b,1.05,-.08,.42,metal);for(let i=0;i<10;i++)b.box([2.95,0,0],[3.8,.07,.1],dark,i*Math.PI/5);const count=Math.max(200,this.slots.length);for(let i=0;i<count;i++){const angle=i*Math.PI*2/count,slot=this.slots[i]||{id:i+1,full:false},active=slot.id===this.selected||slot.id===this.active,r=4.86;b.box([Math.cos(angle)*r,.18,Math.sin(angle)*r],[.42,active ? .45 : .23,.025],active?this.rgba('#e6f5ff'):rail,-angle);if((slot.full||slot.inDrive)&&slot.id!==this.hiddenSlot)this.addDisc(b,angle,active?this.rgba('#dff4ff'):this.colorFor(slot))}this.upload(this.carouselMesh,b);this.buildMachine();this.buildMovingDisc()}
  buildMachine(){const b=this.builder(),frame=this.rgba('#3d5269'),body=this.rgba('#182536'),edge=this.rgba('#70849a'),gate=this.rgba('#243b50');b.box([0,1.35,0],[2.05,2.85,.62],body);b.box([1.06,1.35,0],[.08,2.42,.34],this.rgba('#060a10'));b.box([0,2.88,0],[1.35,.18,.82],edge);b.box([6.22,1.2,0],[.18,2.85,2.72],gate);b.box([6.11,1.2,-1.42],[.45,3.05,.12],edge);b.box([6.11,1.2,1.42],[.45,3.05,.12],edge);for(const x of[-6.35,6.45])for(const z of[-5.55,5.55])b.box([x,1.5,z],[.1,3.35,.1],frame);for(const y of[-.15,3.15]){b.box([.05,y,-5.55],[12.8,.1,.1],frame);b.box([.05,y,5.55],[12.8,.1,.1],frame);b.box([-6.35,y,0],[.1,.1,11.1],frame);b.box([6.45,y,0],[.1,.1,11.1],frame)}this.upload(this.machineMesh,b)}
  buildMovingDisc(){const b=this.builder();this.addDisc(b,0,this.rgba('#e9f7ff'),1.12,0,0,0.025);this.upload(this.movingMesh,b)}
  setupInput(){const c=this.canvas;c.addEventListener('pointerdown',e=>{this.dragging=true;this.dragDistance=0;this.lastPointer=[e.clientX,e.clientY];c.setPointerCapture(e.pointerId);c.classList.add('dragging')});c.addEventListener('pointermove',e=>{if(!this.dragging)return;const dx=e.clientX-this.lastPointer[0],dy=e.clientY-this.lastPointer[1];this.dragDistance+=Math.abs(dx)+Math.abs(dy);this.cameraYaw+=dx*.008;this.cameraPitch=Math.max(.12,Math.min(1.22,this.cameraPitch+dy*.006));this.lastPointer=[e.clientX,e.clientY]});c.addEventListener('pointerup',e=>{this.dragging=false;c.classList.remove('dragging');if(this.dragDistance<8)this.pick(e.clientX,e.clientY)});c.addEventListener('pointercancel',()=>{this.dragging=false;c.classList.remove('dragging')});c.addEventListener('wheel',e=>{e.preventDefault();this.distance=Math.max(9,Math.min(23,this.distance+e.deltaY*.012))},{passive:false});c.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const delta=e.key==='ArrowLeft'?-1:1;this.select(Math.max(1,Math.min(200,(this.selected||this.active||1)+delta)))}});if(window.ResizeObserver)new ResizeObserver(()=>this.resize()).observe(c);else addEventListener('resize',()=>this.resize())}
  resize(){if(!this.gl)return;const ratio=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(this.canvas.clientWidth*ratio)),h=Math.max(1,Math.round(this.canvas.clientHeight*ratio));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.gl.viewport(0,0,w,h)}}
  update(state){if(!this.gl)return;const previous=this.slots.length?new Map(this.slots.map(s=>[s.id,s])):null,oldDrive=this.state&&this.state.drive;this.state=state;this.slots=state.slots||[];const job=state.carouselJob||state.job,drive=state.drive||{state:'empty'},nextActive=Number(job&&job.slot)||Number(drive.slot)||0;if(nextActive&&nextActive!==this.active){this.active=nextActive;this.focusSlot(nextActive)}if(previous){for(const slot of this.slots){const old=previous.get(slot.id);if(!old||old.full===slot.full)continue;const mode=state.carouselJob&&state.carouselJob.mode;if(slot.full&&!old.full)this.startTransfer(slot.id,mode==='load'?'gate':'drive','carousel');else if(!slot.full&&old.full)this.startTransfer(slot.id,'carousel',mode==='unload'?'gate':'drive')}}if(oldDrive&&oldDrive.state!=='empty'&&drive.state==='empty'&&drive.slot)this.startTransfer(drive.slot,'drive','carousel');this.rebuild();this.updateInspector()}
  focusSlot(slot){this.targetCarouselAngle=this.nearestAngle((slot-1)*Math.PI*2/200,this.carouselAngle)}
  nearestAngle(target,current){while(target-current>Math.PI)target-=Math.PI*2;while(target-current < -Math.PI)target+=Math.PI*2;return target}
  startTransfer(slot,from,to){this.active=slot;this.focusSlot(slot);this.transfer={slot,from,to,start:performance.now(),duration:1450};this.hiddenSlot=to==='carousel'?slot:0;this.rebuild()}
  select(slot){this.selected=slot;this.focusSlot(slot);this.rebuild();this.updateInspector()}
  updateInspector(){const slot=this.slots.find(s=>s.id===(this.selected||this.active)),title=document.getElementById('carouselInspectorTitle'),detail=document.getElementById('carouselInspectorDetail');if(!slot){title.textContent='No slot selected';detail.textContent='Select a disc to inspect its live state.';updateSlotActionControls(null);return}title.textContent='Slot '+slot.id;const parts=[slot.inDrive?'In optical drive':slot.full?'Disc stored':'Empty'];if(slot.full||slot.inDrive)parts.push(slot.label||slot.discType||'Unscanned');if(slot.backupStatus==='ripped')parts.push('Ripped');if(slot.exception)parts.push('Hardware exception');detail.textContent=parts.join(' · ');updateSlotActionControls(slot)}
  reset(){this.cameraYaw=-.68;this.cameraPitch=.48;this.distance=14.5;if(this.active)this.focusSlot(this.active)}
  toggleMotion(){this.motion=!this.motion;return this.motion}
  frame(time){if(!this.gl)return;const dt=Math.min(.05,(time-this.lastTime)/1000);this.lastTime=time;if(this.motion&&!this.dragging&&!this.active&&!this.selected)this.cameraYaw+=dt*.055;const d=this.targetCarouselAngle-this.carouselAngle;this.carouselAngle+=d*Math.min(1,dt*4.2);if(Math.abs(d)<.0005)this.carouselAngle=this.targetCarouselAngle;if(this.transfer&&(time-this.transfer.start)>=this.transfer.duration){this.hiddenSlot=0;this.transfer=null;this.rebuild()}this.draw(time);requestAnimationFrame(t=>this.frame(t))}
  draw(time){const gl=this.gl;this.resize();gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(this.program);const eye=[Math.sin(this.cameraYaw)*Math.cos(this.cameraPitch)*this.distance,Math.sin(this.cameraPitch)*this.distance,Math.cos(this.cameraYaw)*Math.cos(this.cameraPitch)*this.distance],vp=this.mul(this.perspective(Math.PI/4,this.canvas.width/this.canvas.height,.1,80),this.lookAt(eye,[0,1,0],[0,1,0]));gl.uniformMatrix4fv(this.locations.vp,false,vp);this.drawMesh(this.carouselMesh,this.rotateY(this.carouselAngle));this.drawMesh(this.machineMesh,this.identity());if(this.transfer){const raw=Math.min(1,(time-this.transfer.start)/this.transfer.duration),p=raw<.5?2*raw*raw:1-Math.pow(-2*raw+2,2)/2,positions={carousel:[3.72,1.3,0],drive:[.35,1.3,0],gate:[6.75,1.3,0]},a=positions[this.transfer.from],b=positions[this.transfer.to],lift=Math.sin(p*Math.PI)*.32,pos=[a[0]+(b[0]-a[0])*p,a[1]+(b[1]-a[1])*p+lift,0],model=this.mul(this.translate(pos),this.scale([1,1,1]));this.drawMesh(this.movingMesh,model)}this.updatePickPoints(vp)}
  drawMesh(mesh,model){if(!mesh.count)return;const gl=this.gl,stride=40;gl.uniformMatrix4fv(this.locations.model,false,model);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.vertex);gl.enableVertexAttribArray(this.locations.position);gl.vertexAttribPointer(this.locations.position,3,gl.FLOAT,false,stride,0);gl.enableVertexAttribArray(this.locations.normal);gl.vertexAttribPointer(this.locations.normal,3,gl.FLOAT,false,stride,12);gl.enableVertexAttribArray(this.locations.color);gl.vertexAttribPointer(this.locations.color,4,gl.FLOAT,false,stride,24);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,mesh.index);gl.drawElements(gl.TRIANGLES,mesh.count,gl.UNSIGNED_SHORT,0)}
  updatePickPoints(vp){const model=this.rotateY(this.carouselAngle),m=this.mul(vp,model),w=this.canvas.clientWidth,h=this.canvas.clientHeight;this.pickPoints=this.slots.filter(s=>s.full||s.inDrive).map(s=>{const a=(s.id-1)*Math.PI*2/200,v=this.transform(m,[Math.cos(a)*3.72,1.3,Math.sin(a)*3.72,1]);return{id:s.id,x:(v[0]/v[3]*.5+.5)*w,y:(1-(v[1]/v[3]*.5+.5))*h,z:v[2]/v[3]}}).filter(p=>p.z<1)}
  pick(clientX,clientY){const r=this.canvas.getBoundingClientRect(),x=clientX-r.left,y=clientY-r.top;let best=null;for(const p of this.pickPoints){const d=Math.hypot(p.x-x,p.y-y);if(d<28&&(!best||d<best.d))best={id:p.id,d}}if(best)this.select(best.id)}
  identity(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])}
  mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let v=0;for(let k=0;k<4;k++)v+=a[k*4+r]*b[c*4+k];o[c*4+r]=v}return o}
  perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0])}
  lookAt(eye,target,up){let z=this.norm([eye[0]-target[0],eye[1]-target[1],eye[2]-target[2]]),x=this.norm(this.cross(up,z)),y=this.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-this.dot(x,eye),-this.dot(y,eye),-this.dot(z,eye),1])}
  rotateY(a){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,0,-s,0,0,1,0,0,s,0,c,0,0,0,0,1])}
  translate(v){const m=this.identity();m[12]=v[0];m[13]=v[1];m[14]=v[2];return m}
  scale(v){const m=this.identity();m[0]=v[0];m[5]=v[1];m[10]=v[2];return m}
  transform(m,v){return[m[0]*v[0]+m[4]*v[1]+m[8]*v[2]+m[12]*v[3],m[1]*v[0]+m[5]*v[1]+m[9]*v[2]+m[13]*v[3],m[2]*v[0]+m[6]*v[1]+m[10]*v[2]+m[14]*v[3],m[3]*v[0]+m[7]*v[1]+m[11]*v[2]+m[15]*v[3]]}
  dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}
  cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
  norm(v){const l=Math.hypot(v[0],v[1],v[2])||1;return[v[0]/l,v[1]/l,v[2]/l]}
}
let carousel3D=null;
function ensureCarousel3D(){if(!carousel3D)carousel3D=new DiscbotCarousel3D($('carouselCanvas'),$('carouselWebGLFallback'));return carousel3D}
function updateCarousel3D(state){ensureCarousel3D().update(state)}
function resetCarouselView(){ensureCarousel3D().reset()}
function toggleCarouselMotion(){const running=ensureCarousel3D().toggleMotion(),button=$('carouselMotionButton');button.setAttribute('aria-pressed',String(running));button.textContent=running?'Pause motion':'Resume motion'}
"""#
}
